# LaTeX2HTML 96.1-h (September 30, 1996)
# Associate images original text with physical files.

$key = q/{_inline}$f_F,lambdaneq0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=63 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3335" SRC="img211.gif">|; 
$key = q/{_inline}$[p]bigtriangledown_(lambda)=bigtriangledown_F(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=147 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3581" SRC="img256.gif">|; 
$key = q/{_inline}$rmSpec(R)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=64 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4205" SRC="img416.gif">|; 
$key = q/{_inline}$underlinepsi${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=13 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2765" SRC="img103.gif">|; 
$key = q/{_inline}$i,jinmathbbN${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=60 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline4115" SRC="img394.gif">|; 
$key = q/{_inline}$lgeqj${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=38 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3357" SRC="img218.gif">|; 
$key = q/{_inline}$lambdainLambda_p^-${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=55 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3741" SRC="img300.gif">|; 
$key = q/{displaymath}array|cc||c|c|c|hlinemulticolumn5|c|mboxGlobalDecompositionMatrixofcalS_3hline;SPMamp;L_(lambda);SPMamp;lambda_1;SPMamp;lambda_2;SPMamp;lambda_3bigtriangledown_(lambda);SPMamp;;SPMamp;(1^3);SPMamp;(2,1);SPMamp;(3)hlinehlinelambda_1;SPMamp;(1^3);SPMamp;1-[6];SPMamp;[3];SPMamp;[2]hlinelambda_2;SPMamp;(2,1);SPMamp;;SPMamp;1;SPMamp;[3]hlinelambda_3;SPMamp;(3);SPMamp;;SPMamp;;SPMamp;1hlinearray{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=403 HEIGHT=145 ALIGN=BOTTOM ALT="displaymath3912" SRC="img386.gif">|; 
$key = q/{_inline}$R:=mathbbZ[q,q^-1]${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=109 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline4201" SRC="img415.gif">|; 
$key = q/{_inline}$muinLambda_p^-${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=57 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3573" SRC="img254.gif">|; 
$key = q/{_inline}$jgeqi,lambdainLambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=97 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3787" SRC="img314.gif">|; 
$key = q/{displaymath}[p]bigtriangledown_(lambda)=sum_muinLambda_pa_lambdamu,p[p]bigtriangledown_(mu).{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=372 HEIGHT=44 ALIGN=BOTTOM ALT="displaymath3015" SRC="img301.gif">|; 
$key = q/{_inline}$calK_sigma=epsilon(calK_tau)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=92 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3725" SRC="img295.gif">|; 
$key = q/{_inline}$ainA${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=46 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3311" SRC="img207.gif">|; 
$key = q/{_inline}$tau(X_lambda):=bigtriangledown_(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=120 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3703" SRC="img287.gif">|; 
$key = q/{_inline}$(d_^lambdamu)'${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=44 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3605" SRC="img265.gif">|; 
$key = q/{_inline}$M_Q${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=26 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3527" SRC="img244.gif">|; 
$key = q/{_inline}$linmathbbN${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=42 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2443" SRC="img43.gif">|; 
$key = q/{_inline}$u_lambda_1,2=X_lambda_1-X_lambda_3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=143 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline4107" SRC="img390.gif">|; 
$key = q/{_inline}$g^lambdamuinunderlineR^+${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=73 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3567" SRC="img251.gif">|; 
$key = q/{_inline}$mathbbS_A${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=21 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2309" SRC="img19.gif">|; 
$key = q/{_inline}$i=1,ldots,n-1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=124 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3963" SRC="img353.gif">|; 
$key = q/{displaymath}bigtriangledown_(lambda_n-1)=L_(lambda_n-1)+[n]L_(lambda_n).{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=378 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath3911" SRC="img376.gif">|; 
$key = q/{_inline}$underlineR_p${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3451" SRC="img231.gif">|; 
$key = q/{_inline}$bigtriangleup_(lambda_1)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=48 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4063" SRC="img381.gif">|; 
$key = q/{_inline}$rmres_F${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=33 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline2981" SRC="img151.gif">|; 
$key = q/{_inline}$r,ainunderlineR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=63 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2929" SRC="img139.gif">|; 
$key = q/{_inline}${bigtriangledown_F(mu)|;muinLambda_p}${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=136 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3735" SRC="img298.gif">|; 
$key = q/{_inline}$P_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=19 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3539" SRC="img246.gif">|; 
$key = q/{_inline}$rmmod_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=46 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2293" SRC="img16.gif">|; 
$key = q/{_inline}$rho:RrightarrowS${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2775" SRC="img107.gif">|; 
$key = q/{_inline}$f_K,muneq0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=65 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3097" SRC="img171.gif">|; 
$key = q/{_inline}$x:=sum_lambdainLambdab_lambdaX_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=130 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3777" SRC="img311.gif">|; 
$key = q/{_inline}$MinmathbbS_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=64 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2599" SRC="img65.gif">|; 
$key = q/{_inline}$underlineR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2393" SRC="img35.gif">|; 
$key = q/{_inline}$underlineA_S${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=24 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2771" SRC="img106.gif">|; 
$key = q/{_inline}$calK_tau'subseteqcalK_tau${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=70 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3775" SRC="img310.gif">|; 
$key = q/{_inline}$mathbbZcalS_4${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=30 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2265" SRC="img15.gif">|; 
$key = q/{_inline}$b_isigma=b_i-1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=78 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline4015" SRC="img368.gif">|; 
$key = q/{_inline}$underlineR^+${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=23 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline3265" SRC="img199.gif">|; 
$key = q/{_inline}$(3,lambda_1)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=48 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4105" SRC="img389.gif">|; 
$key = q/{_inline}$lambda_1:=(1^4),;lambda_2:=(2,1^2),;lambda_3:=(2,2),;lambda_4:=(3,1)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=398 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline4123" SRC="img397.gif">|; 
$key = q/{eqnarray*}epsilon(u_lambda_1,2);SPMamp;=;SPMamp;X_lambda_1+[3]X_lambda_3+([8]-1)X_lambda_5epsilon(u_lambda_1,3);SPMamp;=;SPMamp;X_lambda_1+([3]-1)X_lambda_3-[2]X_lambda_4+([8]-[3]+1)X_lambda_5epsilon(u_lambda_2,2);SPMamp;=;SPMamp;X_lambda_2+([8]-1)X_lambda_4+([2]-[4])X_lambda_5epsilon(u_lambda_3,2);SPMamp;=;SPMamp;X_lambda_3+([2]-1)X_lambda_4+([3]-[4]+1)X_lambda_5.{eqnarray*}/;
$cached_env_img{$key} = q|<IMG WIDTH=500 HEIGHT=104 ALIGN=BOTTOM ALT="eqnarray938" SRC="img414.gif">|; 
$key = q/{_inline}$FinmathbbF_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=57 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2745" SRC="img97.gif">|; 
$key = q/{_inline}$F=R_P(p)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=96 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3453" SRC="img232.gif">|; 
$key = q/{_inline}$A_F${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=23 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2751" SRC="img99.gif">|; 
$key = q/{_inline}$lambdaneqmu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=45 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3085" SRC="img168.gif">|; 
$key = q/{_inline}$Lambda=Lambda(n)^+${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=86 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline3929" SRC="img345.gif">|; 
$key = q/{_inline}$calL=underlineA^infty${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=65 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3253" SRC="img197.gif">|; 
$key = q/{_inline}$lambda_0inLambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=54 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3791" SRC="img315.gif">|; 
$key = q/{_inline}$z:=x-yincalK_tau${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=127 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3839" SRC="img328.gif">|; 
$key = q/{displaymath}2left(arrayrrr3;SPMamp;1;SPMamp;-11;SPMamp;3;SPMamp;1-1;SPMamp;1;SPMamp;3arrayright){displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=322 HEIGHT=69 ALIGN=BOTTOM ALT="displaymath3915" SRC="img409.gif">|; 
$key = q/{_inline}${bigtriangledown_F(lambda)|;lambdainLambda_p}${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=136 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3885" SRC="img340.gif">|; 
$key = q/{_inline}$widetildeunderlinepsi(I_A)subseteqI_A_S${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=98 HEIGHT=38 ALIGN=MIDDLE ALT="tex2html_wrap_inline2613" SRC="img73.gif">|; 
$key = q/{_inline}$e_ipi:=e_pi^-1(i)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=101 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline3955" SRC="img351.gif">|; 
$key = q/{_inline}$k^i_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=16 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline3343" SRC="img213.gif">|; 
$key = q/{_inline}$d_^mumu=1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=59 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline3733" SRC="img297.gif">|; 
$key = q/{_inline}$f_lambda(b_1)=3!b^*_1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=101 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4065" SRC="img382.gif">|; 
$key = q/{displaymath}L_(lambda):=bigtriangledown_(lambda)-T_(lambda);;inunderlineA.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=362 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath3010" SRC="img193.gif">|; 
$key = q/{_inline}$N^i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=20 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline2933" SRC="img140.gif">|; 
$key = q/{_inline}$T(lambda_2)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=44 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4151" SRC="img404.gif">|; 
$key = q/{_inline}$[q]rmres_p(a)=[q]a${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=126 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2951" SRC="img147.gif">|; 
$key = q/{_inline}$calL${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=12 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline3243" SRC="img196.gif">|; 
$key = q/{_inline}$rmres_p(ra)=rmres_p(r)rmres_p(a)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=197 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2927" SRC="img138.gif">|; 
$key = q/{_inline}$R:=mathbbZ[x,x^-1]${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=112 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline2983" SRC="img152.gif">|; 
$key = q/{displaymath}f_lambda:bigtriangleup_(lambda)rightarrowbigtriangledown_(lambda).{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=326 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath3007" SRC="img163.gif">|; 
$key = q/{_inline}$f_lambda:bigtriangleup_(lambda)rightarrowbigtriangledown_(lambda)=rmHom_mathbbZ(bigtriangleup_(lambda),mathbbZ)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=301 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3975" SRC="img355.gif">|; 
$key = q/{_inline}$mathbbS_psi:mathbbS_ArightarrowmathbbS_A_S${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=117 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2607" SRC="img71.gif">|; 
$key = q/{_inline}$d_K^lambdamuneq0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=59 HEIGHT=36 ALIGN=MIDDLE ALT="tex2html_wrap_inline3107" SRC="img173.gif">|; 
$key = q/{_inline}$h_lambda,pinmathbbZ${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=64 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3835" SRC="img325.gif">|; 
$key = q/{_inline}$widetildeunderlineR:=mathbbZmathbbS_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=79 HEIGHT=37 ALIGN=MIDDLE ALT="tex2html_wrap_inline2343" SRC="img24.gif">|; 
$key = q/{_inline}$I^i=I^i-1capN^i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=114 HEIGHT=17 ALIGN=BOTTOM ALT="tex2html_wrap_inline2937" SRC="img141.gif">|; 
$key = q/{_inline}$[p]L_(lambda)=L_F(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=130 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3583" SRC="img257.gif">|; 
$key = q/{_inline}$e_1,ldots,e_n${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=74 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline3951" SRC="img350.gif">|; 
$key = q/{_inline}$[p]rmres_p^i-1(c_lambda)=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=128 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3851" SRC="img331.gif">|; 
$key = q/{_inline}$F:=R(p,x-1)congGF(p)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=221 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2989" SRC="img153.gif">|; 
$key = q/{displaymath}[q]rmres_q^i(tau([p^l]u_lambda,p))=[q]rmres_q^i([p^l])(bigtriangledown_(lambda)-sum_muinLambda_pa_lambdamu,pbigtriangledown_(mu)).{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=483 HEIGHT=44 ALIGN=BOTTOM ALT="displaymath3017" SRC="img307.gif">|; 
$key = q/{_inline}$rmres_C${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=33 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline2847" SRC="img123.gif">|; 
$key = q/{_inline}$psi${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=11 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3161" SRC="img186.gif">|; 
$key = q/{_inline}$I_S^0={0}${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=69 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline2797" SRC="img116.gif">|; 
$key = q/{_inline}$phi_lambda_n${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=25 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline4037" SRC="img374.gif">|; 
$key = q/{_inline}$underlinevarphi${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=13 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline2631" SRC="img80.gif">|; 
$key = q/{_inline}$rmres_F(V)congV${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=103 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3003" SRC="img158.gif">|; 
$key = q/{_inline}$M_f${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=24 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3501" SRC="img239.gif">|; 
$key = q/{displaymath}psi:=Sotimes_R-:rmmod_Arightarrowrmmod_A_S{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=375 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath2552" SRC="img70.gif">|; 
$key = q/{_inline}$U,U',U''inmathbbS_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=115 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2365" SRC="img28.gif">|; 
$key = q/{_inline}$[n]=[p_1^l_1]+[p_2^l_2]+ldots+[p_k^l_k]${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=228 HEIGHT=37 ALIGN=MIDDLE ALT="tex2html_wrap_inline2487" SRC="img51.gif">|; 
$key = q/{_inline}$mathbbY_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=25 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2427" SRC="img39.gif">|; 
$key = q/{_inline}$[q]rmres_q^i([p^l])=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=120 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3763" SRC="img308.gif">|; 
$key = q/{_inline}$a_lambdamu,p${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=36 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline3739" SRC="img299.gif">|; 
$key = q/{_inline}$u,vinmathbbS_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=73 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2317" SRC="img20.gif">|; 
$key = q/{_inline}$R_p${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=20 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3437" SRC="img228.gif">|; 
$key = q/{_inline}$e^lambdamu:=d_^lambdamu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=80 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3669" SRC="img280.gif">|; 
$key = q/{_inline}$b_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3831" SRC="img324.gif">|; 
$key = q/{_inline}$[p]rmres_p^i-1([q^i]v_q)=[p][q^i]rmres_p^i-1(v_q)=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=298 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3875" SRC="img335.gif">|; 
$key = q/{_inline}$b_i:=e_i+1-e_i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=110 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3961" SRC="img352.gif">|; 
$key = q/{_inline}$[2]T(lambda_2)=[2](L_(lambda_4)+L_(lambda_5))${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=238 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4187" SRC="img412.gif">|; 
$key = q/{_inline}$rmG_0(A)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=48 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2503" SRC="img54.gif">|; 
$key = q/{_inline}$Box${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=11 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2725" SRC="img94.gif">|; 
$key = q/{_inline}$I^0supseteqI^1supseteqldots${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=106 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline2881" SRC="img129.gif">|; 
$key = q/{displaymath}u_lambda,p:=X_lambda-sum_muinLambda_pa_lambdamu,pX_mu,{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=354 HEIGHT=44 ALIGN=BOTTOM ALT="displaymath3016" SRC="img303.gif">|; 
$key = q/{_inline}$A_K${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=25 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2233" SRC="img8.gif">|; 
$key = q/{_inline}$W(lambda)^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=50 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3119" SRC="img175.gif">|; 
$key = q/{_inline}$varphi:RrightarrowS${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=83 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2579" SRC="img57.gif">|; 
$key = q/{_inline}$rmres_C:mathbbS_RrightarrowmathbbS_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=123 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2829" SRC="img120.gif">|; 
$key = q/{_inline}$sigmacircepsilon=tau${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=70 HEIGHT=9 ALIGN=BOTTOM ALT="tex2html_wrap_inline3713" SRC="img290.gif">|; 
$key = q/{_inline}$f_K,lambdaneq0neqf_K,mu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=124 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3087" SRC="img169.gif">|; 
$key = q/{_inline}$widetildeunderlineR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=37 ALIGN=MIDDLE ALT="tex2html_wrap_inline2355" SRC="img26.gif">|; 
$key = q/{_inline}$A_S${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2643" SRC="img83.gif">|; 
$key = q/{_inline}$d_^lambdalambda:=z_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=72 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3595" SRC="img262.gif">|; 
$key = q/{_inline}$D:=(d_^lambdamu)_lambda,muinLambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=125 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3665" SRC="img278.gif">|; 
$key = q/{_inline}$calS_4${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=17 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2255" SRC="img13.gif">|; 
$key = q/{_inline}$(p,l)neq(q,k)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=104 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2451" SRC="img46.gif">|; 
$key = q/{_inline}$ninR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=47 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2485" SRC="img50.gif">|; 
$key = q/{displaymath}underlinepsi(ra)=underlinevarphi(r)underlinepsi(a);;mboxforallrinunderlineR,;ainunderlineA{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=411 HEIGHT=21 ALIGN=BOTTOM ALT="displaymath2554" SRC="img78.gif">|; 
$key = q/{_inline}$b_itau=b_i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=60 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline4023" SRC="img370.gif">|; 
$key = q/{_inline}$I_S${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=16 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2591" SRC="img63.gif">|; 
$key = q/{_inline}$xinM${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=52 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3305" SRC="img206.gif">|; 
$key = q/{_inline}$rmres_C:underlineArightarrowunderlineA${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=108 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2861" SRC="img125.gif">|; 
$key = q/{_inline}$[p]g^lambdamu=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=77 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3571" SRC="img253.gif">|; 
$key = q/{_inline}$f_K,lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=31 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3077" SRC="img167.gif">|; 
$key = q/{_inline}$iinN_0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=48 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2943" SRC="img143.gif">|; 
$key = q/{_inline}$rmres_p^i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=30 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3371" SRC="img221.gif">|; 
$key = q/{_inline}$i=2,ldots,n-1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=124 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3991" SRC="img360.gif">|; 
$key = q/{_inline}$[3]bigtriangledown_(lambda_1)=[3]L_(lambda_3)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=167 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4077" SRC="img385.gif">|; 
$key = q/{_inline}$d_^lambdamu:=g^lambdamu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline3597" SRC="img263.gif">|; 
$key = q/{_inline}$Minrmmod_A${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=87 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2511" SRC="img55.gif">|; 
$key = q/{_inline}$mathbbS_varphi(U)=V${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=89 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2583" SRC="img60.gif">|; 
$key = q/{_inline}$phi_lambda(a^*x,y)=phi_lambda(x,ay)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=177 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3137" SRC="img182.gif">|; 
$key = q/{_inline}$T_(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=35 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3225" SRC="img192.gif">|; 
$key = q/{_inline}$M=M_f+M_t${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=117 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3499" SRC="img238.gif">|; 
$key = q/{_inline}$underlinevarphi:underlineRrightarrowunderlineQ=mathbbZ${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=124 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3815" SRC="img319.gif">|; 
$key = q/{_inline}$I^0_S${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=16 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline2769" SRC="img105.gif">|; 
$key = q/{_inline}$f_K,lambda=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=65 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3193" SRC="img187.gif">|; 
$key = q/{_inline}$tau${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=8 HEIGHT=8 ALIGN=BOTTOM ALT="tex2html_wrap_inline3719" SRC="img293.gif">|; 
$key = q/{_inline}$rmRes_q(M)=rmRes_q(N)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=162 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3363" SRC="img220.gif">|; 
$key = q/{_inline}$sigma(X_lambda):=L_(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=117 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3701" SRC="img286.gif">|; 
$key = q/{_inline}$underlineA^infty${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=27 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2941" SRC="img142.gif">|; 
$key = q/{_inline}$pinmathbbZ${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=46 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2991" SRC="img154.gif">|; 
$key = q/{_inline}$[p](g^lambdalambda+1)=[p]d_F^lambdalambda=[p]${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=205 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3585" SRC="img258.gif">|; 
$key = q/{_inline}$bigtriangleup_(lambda),bigtriangledown_(lambda)inrmmod_A${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=162 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3047" SRC="img162.gif">|; 
$key = q/{_inline}$bigtriangleup_F(lambda)=[p]bigtriangleup_(lambda)=[p]bigtriangledown_(lambda)=bigtriangledown_F(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=323 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3629" SRC="img271.gif">|; 
$key = q/{_inline}$b_lambda_0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=20 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3803" SRC="img318.gif">|; 
$key = q/{_inline}$lambda_3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=16 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline4061" SRC="img380.gif">|; 
$key = q/{_inline}$q^l${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=12 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline2911" SRC="img135.gif">|; 
$key = q/{_inline}$mathbbZnmathbbZ${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=45 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3999" SRC="img363.gif">|; 
$key = q/{_inline}$f_lambda(x)(y):=phi_lambda(x,y)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=159 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3159" SRC="img185.gif">|; 
$key = q/{_inline}$tau(x)=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=67 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3821" SRC="img323.gif">|; 
$key = q/{_inline}$phi_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=18 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3135" SRC="img181.gif">|; 
$key = q/{_inline}$[p]rmres_p^j(c_lambda)=[p]rmres_p^j(b_lambda)=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=219 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3845" SRC="img330.gif">|; 
$key = q/{_inline}$mathbbY_RcapmathbbX_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=71 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2727" SRC="img95.gif">|; 
$key = q/{_inline}$lambdaleqmu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=45 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3109" SRC="img174.gif">|; 
$key = q/{_inline}$T(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=37 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3993" SRC="img361.gif">|; 
$key = q/{_inline}$nb^*_1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=24 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3987" SRC="img358.gif">|; 
$key = q/{displaymath}rmres_F([U])rmres_F([V])=[F]neq0=rmres_F([U][V]).{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=430 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath2811" SRC="img160.gif">|; 
$key = q/{_inline}$RrightarrowS${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=55 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2657" SRC="img85.gif">|; 
$key = q/{_inline}$I^i-1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=30 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline2891" SRC="img131.gif">|; 
$key = q/{_inline}$(p,lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=40 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4099" SRC="img387.gif">|; 
$key = q/{_inline}$d_K^lambdamu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=24 HEIGHT=36 ALIGN=MIDDLE ALT="tex2html_wrap_inline2235" SRC="img9.gif">|; 
$key = q/{_inline}$I^i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=13 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline2889" SRC="img130.gif">|; 
$key = q/{_inline}$sigma,tau:underlineR^LambdarightarrowunderlineA^infty${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=125 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline3699" SRC="img285.gif">|; 
$key = q/{_inline}$rmG_0(A_K)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=62 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3241" SRC="img195.gif">|; 
$key = q/{_inline}$Lambda_p^-=emptyset${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=58 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline3211" SRC="img190.gif">|; 
$key = q/{_inline}$tau:=(12)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=71 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4009" SRC="img366.gif">|; 
$key = q/{_inline}$rmRes_q(M)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=69 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3327" SRC="img208.gif">|; 
$key = q/{_inline}$tau:mathbbF_SrightarrowmathbbF_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=97 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2777" SRC="img108.gif">|; 
$key = q/{_inline}$rmres_p${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=30 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline2925" SRC="img137.gif">|; 
$key = q/{_inline}$E:=(e^lambdamu)_lambda,muinLambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=122 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3673" SRC="img281.gif">|; 
$key = q/{_inline}$muinLambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=48 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3095" SRC="img170.gif">|; 
$key = q/{_inline}$b^*_1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=13 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3997" SRC="img362.gif">|; 
$key = q/{_inline}$kappa(a):=1_underlineSotimesunderlinepsi'(a)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=147 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2715" SRC="img91.gif">|; 
$key = q/{_inline}$N':=R_pN${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=88 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3443" SRC="img230.gif">|; 
$key = q/{_inline}$[p]g^lambdalambda=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=77 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3587" SRC="img259.gif">|; 
$key = q/{_inline}$rmmod_A${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=45 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2297" SRC="img17.gif">|; 
$key = q/{_inline}$g^lambdalambdainunderlineR^+${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=73 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3589" SRC="img260.gif">|; 
$key = q/{_inline}$Lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=13 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2215" SRC="img4.gif">|; 
$key = q/{_inline}$[p]rmres_p^i+1(M)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=97 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3419" SRC="img226.gif">|; 
$key = q/{displaymath}0rightarrowU'rightarrowUrightarrowU''rightarrow0.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=348 HEIGHT=16 ALIGN=BOTTOM ALT="displaymath2267" SRC="img29.gif">|; 
$key = q/{displaymath}[p]rmres_p^l-1(M)=p^l-1Mp^lMrightarrowp^lMp^l+1M=[p]rmres_p^l(M){displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=475 HEIGHT=25 ALIGN=BOTTOM ALT="displaymath3012" SRC="img215.gif">|; 
$key = q/{_inline}$sigma:=(1234)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=91 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4157" SRC="img406.gif">|; 
$key = q/{_inline}$linrmHom_R(bigtriangleup_(lambda),R),;ainA${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=220 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3125" SRC="img178.gif">|; 
$key = q/{_inline}$h_lambda,p${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=28 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3879" SRC="img337.gif">|; 
$key = q/{_inline}$MinmathbbS_A${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=63 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2625" SRC="img77.gif">|; 
$key = q/{_inline}${L_(lambda)|;lambdainLambda}${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=113 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3271" SRC="img201.gif">|; 
$key = q/{_inline}$underlineA${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=14 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2501" SRC="img53.gif">|; 
$key = q/{_inline}$underlineA_R_p${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=32 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3455" SRC="img233.gif">|; 
$key = q/{_inline}$epsilon(X_lambda):=sum_muinLambdae^lambdamuX_mu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=175 HEIGHT=34 ALIGN=MIDDLE ALT="tex2html_wrap_inline3711" SRC="img289.gif">|; 
$key = q/{_inline}$L_K(mu)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=49 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2241" SRC="img11.gif">|; 
$key = q/{_inline}$NincalL^+${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=61 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline3533" SRC="img245.gif">|; 
$key = q/{_inline}$z_lambda:=1-sum_pinP_lambda[p^l_p]inunderlineR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=202 HEIGHT=34 ALIGN=MIDDLE ALT="tex2html_wrap_inline3543" SRC="img247.gif">|; 
$key = q/{_inline}$d_F^lambdamu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=24 HEIGHT=36 ALIGN=MIDDLE ALT="tex2html_wrap_inline3625" SRC="img270.gif">|; 
$key = q/{_inline}$calK_sigma${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3717" SRC="img292.gif">|; 
$key = q/{_inline}$[F]inunderlineR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=61 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2755" SRC="img100.gif">|; 
$key = q/{displaymath}[p]rmres_p^i(sum_i=1^j(k^i-1_lambda-k^i_lambda)[p^i])=k^i_lambda[p]{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=383 HEIGHT=56 ALIGN=BOTTOM ALT="displaymath3014" SRC="img222.gif">|; 
$key = q/{_inline}$[8]bigtriangledown_(lambda_1)=[8]L_(lambda_5)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=167 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4139" SRC="img402.gif">|; 
$key = q/{_inline}$l_F${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2759" SRC="img102.gif">|; 
$key = q/{_inline}$lambda_5:=(4)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=70 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4125" SRC="img398.gif">|; 
$key = q/{_inline}$rmres_C^i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=33 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline2865" SRC="img126.gif">|; 
$key = q/{_inline}$underlineA^0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=20 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline2799" SRC="img117.gif">|; 
$key = q/{displaymath}underlinepsi(tau(x))=sum_lambdainLambdaunderlinevarphi(b_lambda)bigtriangledown_Q(lambda)neq0{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=379 HEIGHT=42 ALIGN=BOTTOM ALT="displaymath3018" SRC="img321.gif">|; 
$key = q/{_inline}$mathbbX_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=25 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2409" SRC="img38.gif">|; 
$key = q/{_inline}$T(lambda)=sum_muinLambdag^lambdamuL_(mu)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=178 HEIGHT=34 ALIGN=MIDDLE ALT="tex2html_wrap_inline3569" SRC="img252.gif">|; 
$key = q/{_inline}$mathbbZcalS_n${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=32 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline4003" SRC="img364.gif">|; 
$key = q/{_inline}$Lambda_p^-neqemptyset${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=58 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline3729" SRC="img296.gif">|; 
$key = q/{_inline}$mathbbY_RsubseteqmathbbX_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=75 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2437" SRC="img41.gif">|; 
$key = q/{_inline}$bigtriangledown_(lambda)=L_(lambda)+T(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=167 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3577" SRC="img255.gif">|; 
$key = q/{_inline}$0inmathbbY_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=57 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2473" SRC="img49.gif">|; 
$key = q/{_inline}$A_S:=Sotimes_RA${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=114 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2605" SRC="img69.gif">|; 
$key = q/{_inline}$lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=9 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2213" SRC="img3.gif">|; 
$key = q/{_inline}$b^*_2-b^*_1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=52 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4029" SRC="img372.gif">|; 
$key = q/{_inline}$Ninrmmod_A${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=84 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3519" SRC="img243.gif">|; 
$key = q/{_inline}$phi_lambda(xa,y)=phi_lambda(x,ya^*)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=176 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3147" SRC="img183.gif">|; 
$key = q/{_inline}$f_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=16 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3157" SRC="img184.gif">|; 
$key = q/{_inline}$2(b^*_1-b^*_2+b^*_3)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=114 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4169" SRC="img411.gif">|; 
$key = q/{_inline}$bigtriangleup_(lambda_n)=bigtriangledown_(lambda_n)=L_(lambda_n)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=200 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4039" SRC="img375.gif">|; 
$key = q/{_inline}$8b^*_1,8b^*_2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=55 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4167" SRC="img410.gif">|; 
$key = q/{_inline}$rmres_C(U)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=62 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2841" SRC="img122.gif">|; 
$key = q/{_inline}$b^*_i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=13 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3981" SRC="img357.gif">|; 
$key = q/{_inline}$u_lambda_1,3=X_lambda_1-X_lambda_2+X_lambda_3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=197 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline4109" SRC="img391.gif">|; 
$key = q/{_inline}$(la)(d):=l(da^*)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=130 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3123" SRC="img177.gif">|; 
$key = q/{_inline}$v_qinunderlineR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=54 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3871" SRC="img334.gif">|; 
$key = q/{displaymath}underlinevarphicircunderlinevarphi'=rmid_underlineS;;mboxand;;underlinepsicircunderlinepsi'=rmid_underlineA_S.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=386 HEIGHT=23 ALIGN=BOTTOM ALT="displaymath2558" SRC="img88.gif">|; 
$key = q/{_inline}$rmG_0(A_Q)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=60 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3819" SRC="img322.gif">|; 
$key = q/{_inline}$mathbbI_A${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=18 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2533" SRC="img56.gif">|; 
$key = q/{displaymath}varphi':rmmod_Srightarrowrmmod_R,;;psi':rmmod_A_Srightarrowrmmod_A{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=417 HEIGHT=20 ALIGN=BOTTOM ALT="displaymath2556" SRC="img82.gif">|; 
$key = q/{_inline}$dinbigtriangleup_(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=74 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3127" SRC="img179.gif">|; 
$key = q/{_inline}$kappacircunderlinepsi_S=rmid_${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=91 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2721" SRC="img93.gif">|; 
$key = q/{_inline}$rmres_p:=rmres_F${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=94 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline2903" SRC="img134.gif">|; 
$key = q/{_inline}$[2]bigtriangledown_(lambda_1)=[2]L_(lambda_3)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=167 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4075" SRC="img384.gif">|; 
$key = q/{_inline}$underlinevarphi:underlineRrightarrowunderlineK=mathbbZ${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=126 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3639" SRC="img273.gif">|; 
$key = q/{_inline}$underlineA,underlineA^i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=40 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline3221" SRC="img191.gif">|; 
$key = q/{_inline}$k,linmathbbZ${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=59 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4117" SRC="img395.gif">|; 
$key = q/{_inline}$V:=R(p)congGF(p)[x,x^-1]${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=227 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline2997" SRC="img156.gif">|; 
$key = q/{_inline}$rmres_p^0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=30 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline2949" SRC="img146.gif">|; 
$key = q/{_inline}$[q]rmres_p^i(a)=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=105 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline2947" SRC="img145.gif">|; 
$key = q/{displaymath}Urightarrow(RI)otimes_RU,;;umapsto1otimesu,{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=372 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath2807" SRC="img121.gif">|; 
$key = q/{_inline}$mathbbY_Rbackslash{0}${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=61 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2433" SRC="img40.gif">|; 
$key = q/{displaymath}rmRes_2(T(lambda_2))=([2](L_(lambda_4)+L_(lambda_5)),[2]L_(lambda_4),[2]L_(lambda_4),0,ldots){displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=492 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath3916" SRC="img413.gif">|; 
$key = q/{_inline}$rmRes_p(x):=([p]rmres_p^i(x),[p]rmres_p^1(x),ldots)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=295 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3283" SRC="img204.gif">|; 
$key = q/{_inline}$rmres_F(U)congU${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=103 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3001" SRC="img157.gif">|; 
$key = q/{_inline}$L_(lambda)=z_lambdaL_(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=118 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3603" SRC="img264.gif">|; 
$key = q/{_inline}$f_K,lambdaneq0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=65 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3205" SRC="img189.gif">|; 
$key = q/{_inline}$[p^l]${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=20 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline2449" SRC="img45.gif">|; 
$key = q/{_inline}$g^lambdalambda=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=59 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3591" SRC="img261.gif">|; 
$key = q/{_inline}$widetildeunderlinevarphi:widetildeunderlineRrightarrowwidetildeunderlineS${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=85 HEIGHT=38 ALIGN=MIDDLE ALT="tex2html_wrap_inline2587" SRC="img62.gif">|; 
$key = q/{_inline}$rmRes_p(M)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=69 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3329" SRC="img209.gif">|; 
$key = q/{_inline}$X_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=23 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3693" SRC="img283.gif">|; 
$key = q/{_inline}$underlinepsi_Scirckappa=rmid_${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=92 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2719" SRC="img92.gif">|; 
$key = q/{_inline}$rmRes_q^i(tau([p^l]u_lambda,p))=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=163 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline3771" SRC="img309.gif">|; 
$key = q/{_inline}$UinmathbbS_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=59 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2623" SRC="img76.gif">|; 
$key = q/{_inline}$l_S${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=14 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2689" SRC="img89.gif">|; 
$key = q/{_inline}$ainunderlineA${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=46 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2787" SRC="img112.gif">|; 
$key = q/{_inline}$widetildeunderlineA${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=14 HEIGHT=37 ALIGN=MIDDLE ALT="tex2html_wrap_inline2347" SRC="img25.gif">|; 
$key = q/{_inline}$calK_tau${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=21 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3715" SRC="img291.gif">|; 
$key = q/{_inline}$psi:=Sotimes_R-${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=102 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3063" SRC="img164.gif">|; 
$key = q/{_inline}$L_K(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=49 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2231" SRC="img7.gif">|; 
$key = q/{_inline}$[p^l]neq[q^k]${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=73 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline2453" SRC="img47.gif">|; 
$key = q/{_inline}$muinLambda_p${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=55 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3623" SRC="img269.gif">|; 
$key = q/{_inline}$k^i_lambda-k^i+1_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=72 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline3351" SRC="img216.gif">|; 
$key = q/{_inline}$Uotimes_RV${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=62 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2321" SRC="img22.gif">|; 
$key = q/{_inline}$e^lambdalambda:=1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=62 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline3667" SRC="img279.gif">|; 
$key = q/{_inline}$h_lambda,p[p^i]+sum_qneqp[q^i]v_q${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=162 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3869" SRC="img333.gif">|; 
$key = q/{_inline}$calS_n-1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=36 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3941" SRC="img348.gif">|; 
$key = q/{_inline}$jgeqi${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=40 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3797" SRC="img316.gif">|; 
$key = q/{_inline}$calS_n${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=19 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3943" SRC="img349.gif">|; 
$key = q/{_inline}$calS_3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=17 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2253" SRC="img12.gif">|; 
$key = q/{_inline}$n=p_1^l_1p_2^l_2ldotsp_k^l_k${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=125 HEIGHT=37 ALIGN=MIDDLE ALT="tex2html_wrap_inline2489" SRC="img52.gif">|; 
$key = q/{_inline}$I^0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2767" SRC="img104.gif">|; 
$key = q/{_inline}$lambdainLambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=46 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3045" SRC="img161.gif">|; 
$key = q/{_inline}$[p]rmres_p^i-1(c_lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=93 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3889" SRC="img341.gif">|; 
$key = q/{_inline}$Uotimes_RVcongF${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=102 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3005" SRC="img159.gif">|; 
$key = q/{_inline}$I_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=17 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2359" SRC="img27.gif">|; 
$key = q/{_inline}$rinunderlineR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=46 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3257" SRC="img198.gif">|; 
$key = q/{_inline}$T(lambda_1)=[4!]bigtriangledown_(lambda_1)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=154 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4133" SRC="img400.gif">|; 
$key = q/{_inline}$[p]rmres_p^i(M)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3417" SRC="img225.gif">|; 
$key = q/{_inline}$calL^+${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline3267" SRC="img200.gif">|; 
$key = q/{_inline}$e^lambdamu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=24 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline3675" SRC="img282.gif">|; 
$key = q/{_inline}$underlinevarphi(b_lambda_0)neq0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=83 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3817" SRC="img320.gif">|; 
$key = q/{_inline}$lambda_1:=(1^3)=(1,1,1),lambda_2:=(2,1)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=261 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline4047" SRC="img377.gif">|; 
$key = q/{_inline}$[p^l_p]L_(lambda)=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=102 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3547" SRC="img249.gif">|; 
$key = q/{_inline}$rmres_p^l(M)=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=98 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3355" SRC="img217.gif">|; 
$key = q/{_inline}$T(lambda_1)=[3!]bigtriangledown_(lambda_1)=([2]+[3])bigtriangledown_(lambda_1)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=315 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4067" SRC="img383.gif">|; 
$key = q/{_inline}$CinmathbbX_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=62 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2825" SRC="img119.gif">|; 
$key = q/{_inline}$psicircpsi'(M)congM${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=126 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2661" SRC="img87.gif">|; 
$key = q/{_inline}$mathbbS_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2307" SRC="img18.gif">|; 
$key = q/{_inline}$lambda_2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=16 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline4059" SRC="img379.gif">|; 
$key = q/{_inline}$rmres_F^i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=33 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline2875" SRC="img128.gif">|; 
$key = q/{_inline}$x=y+zincalK_tau'${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=122 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3859" SRC="img332.gif">|; 
$key = q/{_inline}$lambda:=lambda_n-1:=(n-1,1)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=182 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3937" SRC="img347.gif">|; 
$key = q/{_inline}$mathbbS_psi(UM)=mathbbS_varphi(U)mathbbS_psi(M)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=199 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2621" SRC="img75.gif">|; 
$key = q/{_inline}$mathbbY_RsubseteqmathbbS_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=72 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2395" SRC="img36.gif">|; 
$key = q/{_inline}$calK_tau'=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=56 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3895" SRC="img342.gif">|; 
$key = q/{_inline}$M':=R_pM${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=95 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3441" SRC="img229.gif">|; 
$key = q/{_inline}$underlineS${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=13 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2627" SRC="img79.gif">|; 
$key = q/{_inline}$U,Vinrmmod_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=104 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2319" SRC="img21.gif">|; 
$key = q/{_inline}$[p]rmres_p^j(b_lambda_0)neq0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=119 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3799" SRC="img317.gif">|; 
$key = q/{_inline}$[p]d_^lambdamuneq0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=77 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3655" SRC="img276.gif">|; 
$key = q/{displaymath}I_RI_AsubseteqI_A.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=293 HEIGHT=16 ALIGN=BOTTOM ALT="displaymath2270" SRC="img33.gif">|; 
$key = q/{_inline}$FinmathbbF_S${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=56 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2785" SRC="img111.gif">|; 
$key = q/{_inline}$[p^l]u_lambda,p${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=52 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3753" SRC="img305.gif">|; 
$key = q/{displaymath}underlineA^0:=underlineAI^0{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=295 HEIGHT=21 ALIGN=BOTTOM ALT="displaymath2561" SRC="img113.gif">|; 
$key = q/{_inline}$b^*_1sigma^-1=b^*_2-b^*_1=b^*_1tau${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=173 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline4027" SRC="img371.gif">|; 
$key = q/{_inline}$lambdainLambda_p${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=53 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3333" SRC="img210.gif">|; 
$key = q/{_inline}$W(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=43 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3133" SRC="img180.gif">|; 
$key = q/{_inline}$bigtriangleup_K(lambda):=Kotimes_Rbigtriangleup_(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=178 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2229" SRC="img6.gif">|; 
$key = q/{_inline}$[p]d_^lambdamu=[p](d_^lambdamu)'${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=134 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3613" SRC="img267.gif">|; 
$key = q/{_inline}$(lambda,p)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=40 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3745" SRC="img302.gif">|; 
$key = q/{displaymath}I^0:={ainunderlineA|;[F]a=0;forallFinmathbbF_R}.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=387 HEIGHT=21 ALIGN=BOTTOM ALT="displaymath2560" SRC="img101.gif">|; 
$key = q/{_inline}$sigma:=(12ldotsn)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=112 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4007" SRC="img365.gif">|; 
$key = q/{_inline}$bigtriangleup_S(lambda),bigtriangledown_S(lambda),f_S,lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=149 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3067" SRC="img166.gif">|; 
$key = q/{_inline}$U:=R(x-1)congmathbbZ${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=163 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2995" SRC="img155.gif">|; 
$key = q/{_inline}$p,qinR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=65 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2945" SRC="img144.gif">|; 
$key = q/{_inline}$A_K:=(Kotimes_RA${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=129 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2227" SRC="img5.gif">|; 
$key = q/{_inline}$l_p${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=12 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3545" SRC="img248.gif">|; 
$key = q/{displaymath}array|cc||c|c|c|c|c|hlinemulticolumn7|c|mboxGlobalDecompositionMatrixofcalS_4hline;SPMamp;L_(lambda);SPMamp;lambda_1;SPMamp;lambda_2;SPMamp;lambda_3;SPMamp;lambda_4;SPMamp;lambda_5bigtriangledown_(lambda);SPMamp;;SPMamp;(1^4);SPMamp;(2,1^2);SPMamp;(2,2);SPMamp;(3,1);SPMamp;(4)hlinehlinelambda_1;SPMamp;(1^4);SPMamp;1-[24];SPMamp;;SPMamp;[3];SPMamp;;SPMamp;[8]hlinelambda_2;SPMamp;(2,1^2);SPMamp;;SPMamp;1-[2];SPMamp;;SPMamp;[8];SPMamp;[2]hlinelambda_3;SPMamp;(2,2);SPMamp;;SPMamp;;SPMamp;1-[2];SPMamp;[2];SPMamp;[3]hlinelambda_4;SPMamp;(3,1);SPMamp;;SPMamp;;SPMamp;;SPMamp;1;SPMamp;[4]hlinelambda_5;SPMamp;(4);SPMamp;;SPMamp;;SPMamp;;SPMamp;;SPMamp;1hlinearray{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=470 HEIGHT=193 ALIGN=BOTTOM ALT="displaymath3914" SRC="img399.gif">|; 
$key = q/{_inline}$L_(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=36 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3229" SRC="img194.gif">|; 
$key = q/{_inline}$d_K^mumu=1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=59 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3105" SRC="img172.gif">|; 
$key = q/{_inline}$varphicircvarphi'(U)congU${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=115 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2659" SRC="img86.gif">|; 
$key = q/{_inline}$bigtriangledown_Q(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=51 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3469" SRC="img235.gif">|; 
$key = q/{_inline}$b^*_i-ib^*_1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=58 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3989" SRC="img359.gif">|; 
$key = q/{displaymath}varphi:=Sotimes_R-:rmmod_Rrightarrowrmmod_S{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=370 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath2549" SRC="img58.gif">|; 
$key = q/{displaymath}(k[2^i]+l[3^j])L_(lambda_1)=l([3^j]-[3])L_(lambda_2)+(k([2^i]-[2])+l([3]-[3^j]))L_(lambda_3).{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=608 HEIGHT=22 ALIGN=BOTTOM ALT="displaymath3913" SRC="img396.gif">|; 
$key = q/{displaymath}bigtriangledown_(lambda):=rmHom_R(bigtriangleup_(lambda),R){displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=351 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath3008" SRC="img176.gif">|; 
$key = q/{_inline}$VcongSotimes_RU${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=101 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2585" SRC="img61.gif">|; 
$key = q/{_inline}$mathbbZ${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=11 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline2257" SRC="img14.gif">|; 
$key = q/{_inline}$b_1tau=-b_1,;b_2tau=b_1+b_2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=197 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4021" SRC="img369.gif">|; 
$key = q/{_inline}$xinunderlineR^+${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=56 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline3275" SRC="img202.gif">|; 
$key = q/{displaymath}I^infty:=bigcap_i=0^inftyI^i;;mboxand;;underlineA^i:=underlineAI^i,;;;underlineA^infty:=underlineAI^infty.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=440 HEIGHT=52 ALIGN=BOTTOM ALT="displaymath2809" SRC="img133.gif">|; 
$key = q/{_inline}$b_lambdainunderlineR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=54 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3781" SRC="img312.gif">|; 
$key = q/{_inline}$mathbbS_varphi:mathbbS_RrightarrowmathbbS_S${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=108 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2581" SRC="img59.gif">|; 
$key = q/{displaymath}underlinevarphi':underlineSrightarrowunderlineR,;;underlinepsi':underlineA_SrightarrowunderlineA.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=356 HEIGHT=22 ALIGN=BOTTOM ALT="displaymath2557" SRC="img84.gif">|; 
$key = q/{_inline}$[p]rmres_p^i-1(c_lambda)=[p]rmres_p^i-1(b_lambda)-[p]h_lambda,p=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=323 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3877" SRC="img336.gif">|; 
$key = q/{_inline}$underlineR^Lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=23 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3697" SRC="img284.gif">|; 
$key = q/{_inline}$T(lambda_3)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=44 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4149" SRC="img403.gif">|; 
$key = q/{_inline}$L_Q(lambda)=bigtriangleup_Q(lambda)=bigtriangledown_Q(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=205 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3517" SRC="img242.gif">|; 
$key = q/{displaymath}Lambda_p:={lambdainLambda|;f_F,lambdaneq0},;;;Lambda_p^-:=LambdabackslashLambda_p,;;;P_lambda:={pinR|;pmboxprim,lambdainLambda_p^-}.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=595 HEIGHT=22 ALIGN=BOTTOM ALT="displaymath3009" SRC="img188.gif">|; 
$key = q/{_inline}$epsilon${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=6 HEIGHT=8 ALIGN=BOTTOM ALT="tex2html_wrap_inline3705" SRC="img288.gif">|; 
$key = q/{_inline}$d_^lambdalambda=(d_^lambdalambda)'${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=95 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3607" SRC="img266.gif">|; 
$key = q/{displaymath}[p]rmres_p^i(M)=sum_lambdainLambda_pk^i_lambda[p]L_(lambda).{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=362 HEIGHT=45 ALIGN=BOTTOM ALT="displaymath3011" SRC="img214.gif">|; 
$key = q/{_inline}$(2,lambda_1)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=48 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4103" SRC="img388.gif">|; 
$key = q/{_inline}$b_1tau=-b_1,;b_2tau=b_3,;b_2tau=b_3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=239 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4163" SRC="img408.gif">|; 
$key = q/{_inline}$qneqp${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=42 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2953" SRC="img148.gif">|; 
$key = q/{_inline}$epsilon(u_lambda_1,3)=X_lambda_1+([3]-1)X_lambda_2+([2]-[3]+1)X_lambda_3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=395 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline4113" SRC="img393.gif">|; 
$key = q/{_inline}$bigtriangleup_K(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=53 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2237" SRC="img10.gif">|; 
$key = q/{_inline}$b_i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=11 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3977" SRC="img356.gif">|; 
$key = q/{_inline}$mathbbF_S={1}${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=73 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2795" SRC="img115.gif">|; 
$key = q/{_inline}$M^lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=27 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline3933" SRC="img346.gif">|; 
$key = q/{_inline}$b_1sigma=-sum_i=1^n-1b_i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=130 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline4013" SRC="img367.gif">|; 
$key = q/{_inline}$b_1sigma=b_1-b_2+b_3,;b_2sigma=b_1,b_3sigma=b_2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=299 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4161" SRC="img407.gif">|; 
$key = q/{displaymath}underlinevarphi:underlineRrightarrowunderlineS.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=294 HEIGHT=21 ALIGN=BOTTOM ALT="displaymath2550" SRC="img64.gif">|; 
$key = q/{_inline}$lambda_3:=(3)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=70 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4049" SRC="img378.gif">|; 
$key = q/{_inline}$0neqd_^lambdamuinunderlineR^+${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=72 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3651" SRC="img275.gif">|; 
$key = q/{_inline}$sigma${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=10 HEIGHT=8 ALIGN=BOTTOM ALT="tex2html_wrap_inline3721" SRC="img294.gif">|; 
$key = q/{_inline}$b_1,b_2,b_3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=61 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4155" SRC="img405.gif">|; 
$key = q/{_inline}$M_Q:=Qotimes_RM${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=127 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3515" SRC="img241.gif">|; 
$key = q/{_inline}$mathbbX_RsubseteqmathbbS_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=72 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2399" SRC="img37.gif">|; 
$key = q/{_inline}$pinR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=48 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2441" SRC="img42.gif">|; 
$key = q/{_inline}$[tau(F)]a=[F]underlinepsi(a)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=144 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2783" SRC="img110.gif">|; 
$key = q/{_inline}$rmG_0(A_S)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=58 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2801" SRC="img118.gif">|; 
$key = q/{displaymath}0rightarrowM'rightarrowMrightarrowM''rightarrow0{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=354 HEIGHT=16 ALIGN=BOTTOM ALT="displaymath2269" SRC="img32.gif">|; 
$key = q/{_inline}$R(p^l)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=50 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline2447" SRC="img44.gif">|; 
$key = q/{displaymath}underlinepsi:underlineArightarrowunderlineA_S.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=300 HEIGHT=21 ALIGN=BOTTOM ALT="displaymath2553" SRC="img74.gif">|; 
$key = q/{_inline}$underlinepsi^0:underlineA^0rightarrowunderlineA_S^0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=117 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline2791" SRC="img114.gif">|; 
$key = q/{_inline}$z=sum_lambdainLambdac_lambdaX_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=124 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline3841" SRC="img329.gif">|; 
$key = q/{_inline}$underlinevarphi(1)=1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=69 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2601" SRC="img67.gif">|; 
$key = q/{_inline}$tau(F):=[Rrho^-1(I)]${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=153 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline2781" SRC="img109.gif">|; 
$key = q/{_inline}$[p]h_lambda,p=[p]rmres_p^i-1(b_lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=168 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3837" SRC="img326.gif">|; 
$key = q/{_inline}$[2]bigtriangledown_(lambda_1)=[2]L_(lambda_5)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=167 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4135" SRC="img401.gif">|; 
$key = q/{_inline}$mathbbF_R${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=21 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2733" SRC="img96.gif">|; 
$key = q/{displaymath}underlineR:=widetildeunderlineRI_R.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=295 HEIGHT=24 ALIGN=BOTTOM ALT="displaymath2268" SRC="img30.gif">|; 
$key = q/{_inline}$xinunderlineR${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=48 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3281" SRC="img203.gif">|; 
$key = q/{_inline}$[p]rmres_p^j(b_lambda)=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=113 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3785" SRC="img313.gif">|; 
$key = q/{_inline}$calK_tau'${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=21 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3749" SRC="img304.gif">|; 
$key = q/{_inline}$rmG_0(A_F)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=60 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3461" SRC="img234.gif">|; 
$key = q/{_inline}$underlineA_F${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=26 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2749" SRC="img98.gif">|; 
$key = q/{_inline}$A_n-1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=37 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3973" SRC="img354.gif">|; 
$key = q/{_inline}$bigtriangleup_(lambda),bigtriangledown_(lambda),f_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=119 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3065" SRC="img165.gif">|; 
$key = q/{displaymath}[p]rmres_p^i-1(tau(z))=sum_lambdainlambda[p]rmres_p^i-1(c_lambda)rmres_p^i-1(bigtriangledown_(lambda))=sum_lambdainLambda_p[p]rmres_p^i-1(c_lambda)[p]bigtriangledown_(lambda)=0,{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=630 HEIGHT=45 ALIGN=BOTTOM ALT="displaymath3020" SRC="img339.gif">|; 
$key = q/{displaymath}y:=sum_lambdainLambdasum_pinP_lambdah_lambda,p[p^i]u_lambda,p;;incalK_tau'.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=375 HEIGHT=44 ALIGN=BOTTOM ALT="displaymath3019" SRC="img327.gif">|; 
$key = q/{_inline}$A:=mathbbZcalS_n${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=77 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3925" SRC="img344.gif">|; 
$key = q/{_inline}$bigtriangledown_(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=41 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2211" SRC="img2.gif">|; 
$key = q/{displaymath}N^i:={ainunderlineA|;rmres_F^i(a)inI^0;;forallFinmathbbF_R}.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=407 HEIGHT=22 ALIGN=BOTTOM ALT="displaymath2808" SRC="img127.gif">|; 
$key = q/{_inline}$underlinevarphi(d_^lambdamu)=d_K^lambdamu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=104 HEIGHT=36 ALIGN=MIDDLE ALT="tex2html_wrap_inline3637" SRC="img272.gif">|; 
$key = q/{_inline}$I^i-1capN^i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=73 HEIGHT=17 ALIGN=BOTTOM ALT="tex2html_wrap_inline2893" SRC="img132.gif">|; 
$key = q/{_inline}$L_F(lambda)=[p]L_(lambda)neq0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=165 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3337" SRC="img212.gif">|; 
$key = q/{displaymath}N:=sum_lambdainLambda_p(sum_i=1^j(k^i-1_lambda-k^i_lambda)[p^i])L_(lambda).{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=389 HEIGHT=60 ALIGN=BOTTOM ALT="displaymath3013" SRC="img219.gif">|; 
$key = q/{_inline}$[p]d_^lambdamu=[p]d_F^lambdamu=[p](d_^lambdamu)'${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=206 HEIGHT=36 ALIGN=MIDDLE ALT="tex2html_wrap_inline3621" SRC="img268.gif">|; 
$key = q/{_inline}$bigtriangleup_(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=41 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2209" SRC="img1.gif">|; 
$key = q/{_inline}$d_F^lambdamuneq0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=59 HEIGHT=36 ALIGN=MIDDLE ALT="tex2html_wrap_inline3657" SRC="img277.gif">|; 
$key = q/{_inline}$M_t${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3503" SRC="img240.gif">|; 
$key = q/{_inline}$epsilon(u_lambda_1,2)=X_lambda_1+[3]X_lambda_2+([2]-1)X_lambda_3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=305 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline4111" SRC="img392.gif">|; 
$key = q/{_inline}$tau(z)=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=67 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3881" SRC="img338.gif">|; 
$key = q/{_inline}$Uotimes_RM${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=67 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2333" SRC="img23.gif">|; 
$key = q/{_inline}$lambda_n:=(n)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=73 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline4035" SRC="img373.gif">|; 
$key = q/{displaymath}underlineA:=widetildeunderlineAI_A{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=292 HEIGHT=24 ALIGN=BOTTOM ALT="displaymath2271" SRC="img34.gif">|; 
$key = q/{_inline}$[p]rmres_p^i(a)=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=106 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline2955" SRC="img149.gif">|; 
$key = q/{_inline}$widetildeunderlinepsi:widetildeunderlineArightarrowwidetildeunderlineA_S${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=96 HEIGHT=38 ALIGN=MIDDLE ALT="tex2html_wrap_inline2611" SRC="img72.gif">|; 
$key = q/{_inline}$MsubseteqN${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=60 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3435" SRC="img227.gif">|; 
$key = q/{_inline}$I_A${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=16 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2381" SRC="img31.gif">|; 
$key = q/{_inline}$rmres_C(M)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=68 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2857" SRC="img124.gif">|; 
$key = q/{displaymath}underlinevarphi([M])=rmdim_S(Sotimes_RM).{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=354 HEIGHT=21 ALIGN=BOTTOM ALT="displaymath2551" SRC="img66.gif">|; 

1;

